#!/usr/bin/env python
# -*- coding: utf-8 -*-
SRC_EMAIL = "THE-GMAIL-ADDRESS-SENDING-THE-MAILS@gmail.com"
SRC_PW = "THE-PASSWORD-FOR-THE-GMAIL-ADDRESS-ABOVE"
DST_EMAIL = "THE-RECIPIENT-EMAIL-ADDRESS"
